### ISSUE TITLE
Sound Problem in menu

### ISSUE THREAD

**Issue by RosaMoses** [darrenefecto/FunTools#1]
In menu after some minutes you have not sound by swapping the categories

**Comment by xXLuShadowkeXx** [comment]
Mine is disappearing after about 2 minutes. How tf can something like this even happen?

**Comment by darrenefecto** [comment]
Hello,
First of all, thanks for playing my game.
So, I took a closer look at the script and I will fix the error tomorrow at the latest.
This Bug happens because I used a wrong Argument which made this bug.
Thank you for reporting this bug!
